### ISSUE TITLE
RuntimeError: expected scalar type Half but found Float

### ISSUE THREAD

**Issue by rbunn80110** [KeremTurgutlu/self_supervised#55]
I think I have almost got training_clip.py working, but ran into this:

Single gpu training mode
vitb32 True <class 'bool'> 2

epoch     train_loss  valid_loss  retrieval_at_5  retrieval_at_20  mean_retrieval_ranking  median_retrieval_ranking  time   
 
Traceback (most recent call last):
  File "/home/bob/PycharmProjects/self_supervised/examples/multimodal/training_clip.py", line 67, in <module>
    def main(
  File "/home/bob/anaconda3/envs/fastai/lib/python3.8/site-packages/fastcore/script.py", line 110, in call_parse
    return _f()
  File "/home/bob/anaconda3/envs/fastai/lib/python3.8/site-packages/fastcore/script.py", line 105, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/home/bob/PycharmProjects/self_supervised/examples/multimodal/training_clip.py", line 150, in main
    else:   learner.fit_flat_cos(epochs, lr, pct_start=0.25)
  File "/home/bob/anaconda3/envs/fastai/lib/python3.8/site-packages/fastai/callback/schedule.py", line 135, in fit_flat_cos
    self.fit(n_epoch, cbs=ParamScheduler(scheds)+L(cbs), reset_opt=reset_opt, wd=wd)
  File "/home/bob/anaconda3/envs/fastai/lib/python3.8/site-packages/fastai/learner.py", line 211, in fit
    self._with_events(self._do_fit, 'fit', CancelFitException, self._end_cleanup)
  File "/home/bob/anaconda3/envs/fastai/lib/python3.8/site-packages/fastai/learner.py", line 160, in _with_events
    try: self(f'before_{event_type}');  f()
  File "/home/bob/anaconda3/envs/fastai/lib/python3.8/site-packages/fastai/learner.py", line 202, in _do_fit
    self._with_events(self._do_epoch, 'epoch', CancelEpochException)
  File "/home/bob/anaconda3/envs/fastai/lib/python3.8/site-packages/fastai/learner.py", line 160, in _with_events
    try: self(f'before_{event_type}');  f()
  File "/home/bob/anaconda3/envs/fastai/lib/python3.8/site-packages/fastai/learner.py", line 196, in _do_epoch
    self._do_epoch_train()
  File "/home/bob/anaconda3/envs/fastai/lib/python3.8/site-packages/fastai/learner.py", line 188, in _do_epoch_train
    self._with_events(self.all_batches, 'train', CancelTrainException)
  File "/home/bob/anaconda3/envs/fastai/lib/python3.8/site-packages/fastai/learner.py", line 160, in _with_events
    try: self(f'before_{event_type}');  f()
  File "/home/bob/anaconda3/envs/fastai/lib/python3.8/site-packages/fastai/learner.py", line 166, in all_batches
    for o in enumerate(self.dl): self.one_batch(*o)
  File "/home/bob/anaconda3/envs/fastai/lib/python3.8/site-packages/fastai/learner.py", line 184, in one_batch
    self._with_events(self._do_one_batch, 'batch', CancelBatchException)
  File "/home/bob/anaconda3/envs/fastai/lib/python3.8/site-packages/fastai/learner.py", line 160, in _with_events
    try: self(f'before_{event_type}');  f()
  File "/home/bob/anaconda3/envs/fastai/lib/python3.8/site-packages/fastai/learner.py", line 177, in _do_one_batch
    self.loss_grad.backward()
  File "/home/bob/anaconda3/envs/fastai/lib/python3.8/site-packages/torch/tensor.py", line 214, in backward
    return handle_torch_function(
  File "/home/bob/anaconda3/envs/fastai/lib/python3.8/site-packages/torch/overrides.py", line 1060, in handle_torch_function
    result = overloaded_arg.__torch_function__(public_api, types, args, kwargs)
  File "/home/bob/anaconda3/envs/fastai/lib/python3.8/site-packages/fastai/torch_core.py", line 329, in __torch_function__
    res = super().__torch_function__(func, types, args=args, kwargs=kwargs)
  File "/home/bob/anaconda3/envs/fastai/lib/python3.8/site-packages/torch/tensor.py", line 995, in __torch_function__
    ret = func(*args, **kwargs)
  File "/home/bob/anaconda3/envs/fastai/lib/python3.8/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/bob/anaconda3/envs/fastai/lib/python3.8/site-packages/torch/autograd/__init__.py", line 130, in backward
    Variable._execution_engine.run_backward(
  File "/home/bob/anaconda3/envs/fastai/lib/python3.8/site-packages/torch/autograd/function.py", line 89, in apply
    return self._forward_cls.backward(self, *args)  # type: ignore
  File "/home/bob/anaconda3/envs/fastai/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 95, in backward
    outputs = ctx.run_function(*detached_inputs)
  File "/home/bob/anaconda3/envs/fastai/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 214, in forward
    input = functions[j](input)
  File "/home/bob/anaconda3/envs/fastai/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/bob/PycharmProjects/self_supervised/self_supervised/multimodal/clip.py", line 248, in forward
    x = x + self.attention(self.ln_1(x))
  File "/home/bob/PycharmProjects/self_supervised/self_supervised/multimodal/clip.py", line 245, in attention
    return self.attn(x, x, x, need_weights=False, attn_mask=self.attn_mask)[0]
  File "/home/bob/anaconda3/envs/fastai/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/bob/anaconda3/envs/fastai/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 978, in forward
    return F.multi_head_attention_forward(
  File "/home/bob/anaconda3/envs/fastai/lib/python3.8/site-packages/torch/nn/functional.py", line 4146, in multi_head_attention_forward
    q, k, v = linear(query, in_proj_weight, in_proj_bias).chunk(3, dim=-1)
  File "/home/bob/anaconda3/envs/fastai/lib/python3.8/site-packages/torch/nn/functional.py", line 1692, in linear
    output = input.matmul(weight.t())
RuntimeError: expected scalar type Half but found Float

**Comment by KeremTurgutlu** [comment]
Pasting error stack doesn't usually help much debugging the issue. Could you please share more details and a reproducible example. Next time please consider using the issue template, thanks!

**Comment by KeremTurgutlu** [comment]
Closing stale issue.
